### ISSUE TITLE
PFP when logged in formatted incorrectly.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-web#116]
![image](https://user-images.githubusercontent.com/69767640/215639036-cfbae00e-165e-460b-847b-73269daed0e0.png)

**Comment by Gigabyte5671** [comment]
Fixed by commit [7f2ea0a](https://github.com/vircadia/vircadia-web/commit/7f2ea0ae07d782eecdea0271400075ed508f58d7).
