### ISSUE TITLE
add movement keys

### ISSUE THREAD

**Issue by Fernandomundolatas** [vircadia/vircadia-web#156]
for an older audience profile perhaps the intuitive keys to move the avatar would be the 4 arrows on the keyboard. 
I would like to make them work the same way as W-A-S-D.
so that the avatar is controlled with both options.

**Comment by Gigabyte5671** [comment]
Hi!

You can use the Controls settings menu to change which keys are bound to each action.
Accessed via `Settings`>`Controls`>`Keyboard`:

![image](https://user-images.githubusercontent.com/22832983/229733129-b68793ed-3c74-4730-8b80-ff8c2c05250a.png)
