### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by atakassamarrentie** [vircadia/vircadia-web#157]
Hello All!

I've got the following error in the browser after successfull build:

**Uncaught TypeError: crypto.randomUUID is not a function**

and the webpage is blank.

node.js version: 16.18.1
npm version: 8.19.2
OS: ubuntu 22.04 LTS

**Comment by Gigabyte5671** [comment]
Hi! Thanks for posting an issue.

Which browser & browser version were you using at the time?

**Comment by Madders** [comment]
I believe this can be closed as I already answered in discord. The reason there was that function only works from browsers when using HTTPS, or the special case trust environment of localhost. see https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by Gigabyte5671** [comment]
Thanks Madders!
