### ISSUE TITLE
if you run the url does not move in real time and the metaverse is disconnected and restarted

### ISSUE THREAD

**Issue by Fernandomundolatas** [vircadia/vircadia-web#161]
if you run the url does not move in real time and this after a few seconds makes the metaverse disconnects and restarts sending you to the starting point of the world. 

this does not happen in other computers in my office, but in 2 computers yes, they are quite normal computers with little age (hp all in, 2 years old). 

this also causes that other avatars do not see your avatar move smoothly, but until the url is not updated the avatar disappears and when you stop running the avatar has changed position, but you do not see the avatar move, but is teleported, auqneu on my computer the avatar if it moves smoothly, but those who see you do not. 

but the most problematic thing is that if you click for a while the world restarts and sends you to the beginning of the world.

greetings

**Comment by Gigabyte5671** [comment]
Hi Fernando, thanks for posting an issue!

This certainly sounds like odd behaviour. If possible, could you please post the specs of the machines you had trouble with. In particular:
- The CPU models
- The RAM capacities
- The browser version numbers

This will allow me to test the app on similar hardware.

---

> but the most problematic thing is that if you click for a while the world restarts and sends you to the beginning of the world.

Can you please elaborate on this as well?

Thanks!
