### ISSUE TITLE
Ambient light setting (adjusted in native) is only "adding" in the web client

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia-web#162]
When the ambient light (from HDR) is set to a value of 0.0, there should be no ambient light visible.  Right now in the web client 0.0 is really 1.0, and anything higher than 0.0 simply adds to it.  For example setting a value of 0.5 is really more like 1.5 on the ambient light intensity.

**Comment by Gigabyte5671** [comment]
@Aitolda Is this still an issue? I think we fixed it in PR #179 (but I may have forgotten to link it to this issue).
