### ISSUE TITLE
Clicking on the right (wrong) things while walking can cause the avatar to permanently walk.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-web#167]
You have to refresh the page to fix that.

**Comment by ctrlaltdavid** [comment]
Repro:
- Have the Chat window open.
- Hold down W to walk forwards.
- While walking, click mouse in Chat window.
- Avatar keeps walking.

It's difficult to stop the avatar from walking but can at least sometimes be done: press A and D several times then D to start walking backward, and can now stop walking.

**Comment by ctrlaltdavid** [comment]
A simpler fix was adopted: retain the use of the `code` property (which in theory is the correct property to use) and upon encountering an `undefined` value. clear the keyboard input state. https://github.com/vircadia/vircadia-web/pull/173

**Comment by ctrlaltdavid** [comment]
PR 173 has been merged.
