### ISSUE TITLE
World looks dark and over-saturated (Post- Babylon 5)

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia-web#176]
After the latest update to the webclient, I noticed ambience was looking really dark. Initially I thought it was to do with with actual ambient light value control, but I think it's not ready the reflectionTexture correctly, causing that HDR to appear very dark, regardless of how high I turn up ambient light.

web-client
![3292ff7402432e943b7b5d82f9bd845b 1](https://github.com/vircadia/vircadia-web/assets/21160271/fdb90143-eb42-4497-b8bd-d499f4d2ffc1)

native-client
![7320a86a2c8e11558f0fb5e4d550103b 1](https://github.com/vircadia/vircadia-web/assets/21160271/e7da142d-bfee-4e71-bff7-971dbc806abb)

Not the glass on the right.  Note how dark the reflections are.

**Comment by Gigabyte5671** [comment]
Fixed by PR #179.
