### ISSUE TITLE
There are hundreds of "NametagBackgroundMaterial" in the material list when viewed with the inspector.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia-web#177]
This COULD be contributing to slowdowns as the inspector appears to shows hundreds of materials being used, despite just a handful in the scene. Needs further investigation on a locally run client.

![0ff6e2952293e02f5dc0d45afe0546b9 1](https://github.com/vircadia/vircadia-web/assets/21160271/36ab8529-b1d7-4328-8c1b-43551004a460)

Worth noting there quite a few "skybox" materials appearing as well.

**Comment by Gigabyte5671** [comment]
We may not be correctly destroying old materials when their parent meshes are removed from the scene. How many of these duplicate materials are there when you first open the app?

**Comment by Aitolda** [comment]
> We may not be correctly destroying old materials when their parent meshes are removed from the scene. How many of these duplicate materials are there when you first open the app?

There's no way to shift-select and get an account, but it's likely hundreds and immediately.

**Comment by Gigabyte5671** [comment]
Yikes, that's not fantastic. Roughly how many chairs (or other interactive meshes) are there in the world?

**Comment by Aitolda** [comment]
> Yikes, that's not fantastic. Roughly how many chairs (or other interactive meshes) are there in the world?
> 
> I think it's the case that we're creating a new instance of the `NametagBackgroundMaterial` for every nametag/label in the scene. This is necessary for player nametags since the display name is in the texture itself. However, for generic labels on chairs (etc) we could memoize and reuse the materials. I'll have a look into this as soon as I can.

Looking at the blend file with anything called "animate_" its 282.  However it's worth noting the sit icon/image actually doesn't seem to appear in this world for whatever reason.

**Comment by Aitolda** [comment]
Winner winner, chicken dinner! (That fixes it).
