### ISSUE TITLE
eslint rule space-before-function-paren should be disabled

### ISSUE THREAD

**Issue by Misterblue** [vircadia/vircadia-web#18]
PR #12 was recently merged into master. Master now fails building because of multiple eslint errors for space-before-function-paran (debug.js, entities.js, metaverse.js). Eslint defaults to wanting function defined like:
    function error (type, string) {
        Log.print(type, 'ERROR', string);
    };
Note the space before the paran and after "function error".
This does not conform to either our CODING_CONVERTIONS document or any normal convention (which is why the new code added had this error).
I suggest .eslintrc.js have "space-before-function-paran" set to "off".

**Comment by ctrlaltdavid** [comment]
I suggest:
```
"space-before-function-paren": [
    "error", {
        "anonymous": "always",
        "named": "never",
        "asyncArrow": "always"
    }
]
```

**Comment by digisomni** [comment]
That can work, yeah.

**Comment by Misterblue** [comment]
The ESLint rules have been updated to be mostly a copy of web-sdk rules. This particular rule has been updated.
