### ISSUE TITLE
Generic sensor API for navigation?

### ISSUE THREAD

**Issue by samuk** [vircadia/vircadia-web#25]
Are you considering using the sensor API for navigation? eg. 
Tilt forward= move forward
Tilt back = move backwards
Tilt left = move left
Tilt right = move right

Standard
https://www.w3.org/TR/generic-sensor/

Demos
https://mobiforge.gitlab.io/sensors/

**Comment by digisomni** [comment]
We're going to have a scripting API available in a future release so this should be covered under that. Plus we are using Babylon.js as the game engine so that might make things easier.
