### ISSUE TITLE
Strings should use backticks ( ` ) instead of quotes.

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-web#27]

**Comment by ctrlaltdavid** [comment]
What is the reason for this proposed change to use backticks?

The linting of the Web app and Web SDK are (or should be) separate, I believe - they both have their own .eslintrc.js files.

**Comment by digisomni** [comment]
Optional is fine, letting one or the other be used is good. I just don't want it to stop people from using backticks really.

**Comment by ctrlaltdavid** [comment]
Backticks are already used in the Web SDK in a few places where their functionality is needed; otherwise, the Web SDK uses double quotes. ESLint rules are set up for this.
