### ISSUE TITLE
Unable to access domain

### ISSUE THREAD

**Issue by fortuneCookieGO** [vircadia/vircadia-web#42]
Dear God, hello!
I run the project on Windows using NPM run dev
The page opened in the browser is fine, the default model is fine,
But when I try to access someone else's domain,
The console says
The WebSocket connection to 'ws: / / 192.168.1.103/10 0, 0,0,0,0:40102' failed:
[networking] Opening domain server connection. Will not send domain server check-in.
I tried all the fields on the list, but the results were the same.
How can I solve this problem?
Looking forward to your reply.

**Comment by Misterblue** [comment]
The web page domain access requires the domain-server to enable webrtc. This is done on the domain-server's admin console.
Also, for audio to work on most browsers, the domain-server must be running with https certificates so the web-socket connection can be wss://

**Comment by loyce-cg** [comment]
Thank you very much!
Enabling WBRTC plus changing the access address solves this problem.
But in connecting to the domain,
My console kept repeating the following two warnings until I shut it down.
**InboundAudioStream.#writeDroppableSilentFrames() not implemented. Frames: 480
AudioClient: AudioStreamStats packet Not processed.**

**Comment by loyce-cg** [comment]
> 网页域访问需要域服务器开启webrtc。这是在域服务器的管理控制台上完成的。 此外，要使音频在大多数浏览器上工作，域服务器必须使用 https 证书运行，因此网络套接字连接可以是 wss:// 另外，不确定 URL。它不接受位置。试试“wss://192.168.1.103:40102”。

Thank you very much!
Enabling WBRTC plus changing the access address solves this problem.
But in connecting to the domain,
My console kept repeating the following two warnings until I shut it down.
InboundAudioStream.#writeDroppableSilentFrames() not implemented. Frames: 480
AudioClient: AudioStreamStats packet Not processed.

**Comment by loyce-cg** [comment]
> The web page domain access requires the domain-server to enable webrtc. This is done on the domain-server's admin console. Also, for audio to work on most browsers, the domain-server must be running with https certificates so the web-socket connection can be wss:// Also, not sure about the URL. It doesn't accept the location. Try "wss://192.168.1.103:40102".

Thank you very much!
Enabling WBRTC plus changing the access address solves this problem.
But in connecting to the domain,
My console kept repeating the following two warnings until I shut it down.
**InboundAudioStream.#writeDroppableSilentFrames() not implemented. Frames: 480
AudioClient: AudioStreamStats packet Not processed.**

**Comment by light42** [comment]
> The web page domain access requires the domain-server to enable webrtc. This is done on the domain-server's admin console. Also, for audio to work on most browsers, the domain-server must be running with https certificates so the web-socket connection can be wss:// Also, not sure about the URL. It doesn't accept the location. Try "wss://192.168.1.103:40102".

Is running the servers from private ssh could affect vircadia-web? Because when I ran everything on my own server the desktop interface is succesfully connected, yet when I use vircadia-web it can't detect the domain. I already enabled the webrtc.

**Comment by Misterblue** [comment]
not sure what's happening there, light42. v-web uses the SDK to open a WebSocket to the URL supplied. If you run v-web with the browser debug console open, what error does it report when the connection is not made?

**Comment by light42** [comment]
I managed to make the websocket responded successfully by turning off websocket ssl.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/6873314/150681415-93dd96a9-8677-4199-ba3e-6f379e9f2977.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/6873314/150681441-7dce808a-5ea5-4aff-b00d-a8049a939f9e.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6873314/150681486-79eff0c2-ad33-4fda-a1fe-a9ce4a01c111.png">
But although it doesn't produced error message anymore it's still stucked in CONNECTING state.

**Comment by light42** [comment]
The domain server logs said that it tried to sent stun requests but it seems that it failed all of it(Timed out after **x** ms without a response, rtt=6000).

**Comment by Gigabyte5671** [comment]
Hey guys! Is this still an issue? If not, I'll go ahead and close it :)
