### ISSUE TITLE
Remove all BABYLON legacy usage.

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia-web#53]
In particular, replace the following with the necessary, explicit imports:
```
import * as BABYLON from "@babylonjs/core/Legacy/legacy";
```

This should reduced the build size., particularly if the most explicit path is used, e.g., instead of:
```
import { AnimationGroup } from "@babylonjs/core";
```
do the following:
```
import { AnimationGroup } from "@babylonjs/core/Animations/animationGroup";
```

The process of doing this should help clear up the TypeScript errors reported in Visual Studio editor - for vscene.ts, in particular.

**Comment by younianhuang** [comment]
All BABYLON legacy usage are removed.
